export default {
    "Prusa MK3S": {
        "default_material": "PLA",
        "default_material_profile": "Prusa PLA",
        "default_quality": "Normal",
        "default_quality_profile": "Normal",
        "default_variant": "0.4mm Nozzle",
        "machine_extruder_trains": {
            "0": "mks3_extruder_0"
        },
        "machine_heated_bed": true,
        "machine_name": "Prusa MKS3",
        "machine_start_gcode": ["M73 P0 R63\n",
                                "M73 Q0 S63\n",
                                "M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2\n",
                                "M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec\n",
                                "M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2\n",
                                "M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec\n",
                                "M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec\n",
                                "M107\n",
                                ";TYPE:Custom\n",
                                'M862.3 P "MK3" ; printer model check\n',
                                "M862.1 P0.4 ; nozzle diameter check\n",
                                "M115 U3.11.0 ; tell printer latest fw version\n",
                                "G90 ; use absolute coordinates\n",
                                "M83 ; extruder relative mode\n",
                                "M104 S215 ; set extruder temp\n",
                                "M140 S60 ; set bed temp\n",
                                "M190 S60 ; wait for bed temp\n",
                                "M109 S215 ; wait for extruder temp\n",
                                "G28 W ; home all without mesh bed level\n",
                                "G80 ; mesh bed leveling\n",
                                "\n",
                                "G1 Z0.2 F720\n",
                                "G1 Y-3 F1000 ; go outside print area\n",
                                "G92 E0.0\n",
                                "G1 X60 E9 F1000 ; intro line\n",
                                "G1 X100 E12.5 F1000 ; intro line\n",
                                "\n",
                                "G92 E0.0\n",
                                "M221 S95 ; set flow to 95%\n",
                                "\n",
                                "; Don't change E values below. Excessive value can damage the printer.\n",
                                "M907 E430 ; set extruder motor current\n",
                                "G21 ; set units to millimeters\n",
                                "G90 ; use absolute coordinates\n",
                                "M83 ; use relative distances for extrusion\n",
                                "M900 K0.05 ; Filament gcode LA 1.5\n",
                                "M900 K30 ; Filament gcode LA 1.0\n",
                                "M107 ; disable fans\n",
                                ";LAYER_CHANGE\n",
                                ";Z:0.2\n",
                                ";HEIGHT:0.2\n",
                                ";BEFORE_LAYER_CHANGE\n",
                                "G92 E0.0\n",   
                                ";0.2\n",
                                "\n",
                                "G1 E-.8 F2100\n",
                                "G1 Z.4 F720\n",
                                ";AFTER_LAYER_CHANGE\n",
                                ";0.2\n",
                                "G1 F800\n"],
        "machine_end_gcode": [  "G1 Z20.00 F720 ; Move print head up\n",
                                "G1 X0 Y200 F3600 ; park head\n",
                                "G4 ; wait\n",
                                "M221 S100 ; reset flow\n",
                                "M900 K0 ; reset LA\n",
                                "M907 E538 ; reset extruder motor current\n",
                                "M104 S0 ; turn off temperature\n",
                                "M140 S0 ; turn off heatbed\n",
                                "M107 ; turn off fan\n",
                                "M84 ; disable motors\n"],
        "machine_width": 200,
        "machine_depth": 200,
        "machine_height": 220,
        "machine_center_is_zero": false,
        "machine_nozzle_size": 0.4,
        "min_layer_height": 0.1,
        "max_layer_height": 1.2,
        "machine_max_feedrate": 300,
        "machine_max_z_slope": 20,
        "extruder_count": 1,
        "extrusion_width": 0.45,
        "extrusion_multiplier": 320,
    },

    "Creality Ender-3":{
        "default_material": "PLA",
        "default_material_profile": "Creality PLA",
        "default_quality": "Normal",
        "default_quality_profile": "Normal",
        "default_variant": "0.4mm Nozzle",
        "machine_extruder_trains": {
            "0": "ender3_extruder_0"
        },
        "machine_heated_bed": true,
        "machine_name": "Creality Ender-3",
        "machine_start_gcode": ["G28 ; home all axes\n",
                                "G1 Z15.0 F9000 ; lift nozzle\n",
                                "G92 E0 ; zero the extruded length\n",
                                "G1 F200 E3 ; extrude 3mm of feed stock\n",
                                "G92 E0 ; zero the extruded length again\n",
                                "G1 F9000\n",
                                "M117 Printing..."],
        "machine_end_gcode": [  "M104 S0 ; turn off extruder\n",
                                "M140 S0 ; turn off bed\n",
                                "G91 ; relative positioning\n",
                                "G1 E-1 F300  ; retract the filament a bit before lifting the nozzle, to release some of the pressure\n",
                                "G1 Z+0.5 E-5 X-20 Y-20 F9000 ; move Z up a bit and retract filament even more\n",
                                "G28 X0 Y0 ; move X/Y to min endstops, so the head is out of the way\n",
                                "M84 ; disable motors\n",
                                "G90 ; absolute positioning\n",
                                "G1 X0 Y200 F3000 ; present print\n",
                                "M117 Printing Done"],
        "machine_width": 220,
        "machine_depth": 220,
        "machine_height": 250,
        "machine_center_is_zero": false,
        "machine_nozzle_size": 0.4,
        "min_layer_height": 0.5,
        "max_layer_height": 1.2,
        "machine_max_feedrate": 300,
        "machine_max_z_slope": 20,
    }
}