export default {
    "Prusa MKS3": {
        "default_material": "PLA",
        "default_material_profile": "Prusa PLA",
        "default_quality": "Normal",
        "default_quality_profile": "Normal",
        "default_variant": "0.4mm Nozzle",
        "machine_extruder_trains": {
            "0": "mks3_extruder_0"
        },
        "machine_heated_bed": true,
        "machine_name": "Prusa MKS3",
        "machine_start_gcode": ["G28 ; home all axes\n",
                                "G1 Z15.0 F9000 ; lift nozzle\n",
                                "G92 E0 ; zero the extruded length\n",
                                "G1 F200 E3 ; extrude 3mm of feed stock\n",
                                "G92 E0 ; zero the extruded length again\n",
                                "G1 F9000\n",
                                "M117 Printing..."],
        "machine_end_gcode": [  "M104 S0 ; turn off extruder\n",
                                "M140 S0 ; turn off bed\n",
                                "G91 ; relative positioning\n",
                                "G1 E-1 F300  ; retract the filament a bit before lifting the nozzle, to release some of the pressure\n",
                                "G1 Z+0.5 E-5 X-20 Y-20 F9000 ; move Z up a bit and retract filament even more\n",
                                "G28 X0 Y0 ; move X/Y to min endstops, so the head is out of the way\n",
                                "M84 ; disable motors\n",
                                "G90 ; absolute positioning\n",
                                "G1 X0 Y200 F3000 ; present print\n",
                                "M117 Printing Done"],
        "machine_width": 250,
        "machine_depth": 250,
        "machine_height": 300,
        "machine_center_is_zero": false,
        "machine_nozzle_size": 0.4,
        "min_layer_height": 0.5,
        "max_layer_height": 1.2,
        "machine_max_feedrate": 300,
        "machine_max_z_slope": 20,
    },

    "Creality Ender-3":{
        "default_material": "PLA",
        "default_material_profile": "Creality PLA",
        "default_quality": "Normal",
        "default_quality_profile": "Normal",
        "default_variant": "0.4mm Nozzle",
        "machine_extruder_trains": {
            "0": "ender3_extruder_0"
        },
        "machine_heated_bed": true,
        "machine_name": "Creality Ender-3",
        "machine_start_gcode": ["G28 ; home all axes\n",
                                "G1 Z15.0 F9000 ; lift nozzle\n",
                                "G92 E0 ; zero the extruded length\n",
                                "G1 F200 E3 ; extrude 3mm of feed stock\n",
                                "G92 E0 ; zero the extruded length again\n",
                                "G1 F9000\n",
                                "M117 Printing..."],
        "machine_end_gcode": [  "M104 S0 ; turn off extruder\n",
                                "M140 S0 ; turn off bed\n",
                                "G91 ; relative positioning\n",
                                "G1 E-1 F300  ; retract the filament a bit before lifting the nozzle, to release some of the pressure\n",
                                "G1 Z+0.5 E-5 X-20 Y-20 F9000 ; move Z up a bit and retract filament even more\n",
                                "G28 X0 Y0 ; move X/Y to min endstops, so the head is out of the way\n",
                                "M84 ; disable motors\n",
                                "G90 ; absolute positioning\n",
                                "G1 X0 Y200 F3000 ; present print\n",
                                "M117 Printing Done"],
        "machine_width": 220,
        "machine_depth": 220,
        "machine_height": 250,
        "machine_center_is_zero": false,
        "machine_nozzle_size": 0.4,
        "min_layer_height": 0.5,
        "max_layer_height": 1.2,
        "machine_max_feedrate": 300,
        "machine_max_z_slope": 20,
    }
}